services:

    # Login form authenticator
    fortress.folk.authenticator.login_form:
        class: Fortress\Folk\Security\LoginFormAuthenticator
        autowire: true
        autoconfigure: true
        arguments:
            $loginRoute: fortress_folk_login
            $redirectRoute: ~

    Fortress\Folk\Security\LoginFormAuthenticator:
        autowire: true
        autoconfigure: true