services:
    # Service defaults
    _default:
        # Explicitly set autowiring and autoconfiguration for services
        autowire: true
        autoconfigure: true

    # Global service inclusion
    Fortress\Folk\Security\LoginFormAuthenticator: ~