services:

    # Global service inclusion
    Fortress\Folk\:
        resources: '../../*.php'                               # Include all .php files in src/
        exclude: '../../{DependencyInjection,Model,Resources}' # Exclude DependencyInjection, Model and Resources
                                                               #  in src/

        # Explicitly set autowiring and autoconfiguration for services
        autowire: true
        autoconfigure: true